### ISSUE TITLE
Joomla trigger after two step verification?

### ISSUE THREAD

**Issue by rbuelund** [akeeba/loginguard#108]
I use community builder and the auto action plugin to redirect the user after login. But it does not work anymore after installing Loginguard because i use the trigger onAfterLogin, which i believe also is triggering Loginguard? - is there another joomla trigger that Loginguard sets off after the two step login, so that i can catch that instead ??

**Comment by nikosdion** [comment]
That’s not how it works. Capturing on after login would be trivially defeatable by visiting another URL when asked for two step verification. 

Our system plugin does some checks on every page load. If you are not logged in no action is taken. If you’re logged in and there’s a server side session flag that’s you’ve gone through 2SV no action is taken. If you’re on a LoginGuard URL no action is taken. 

Otherwise we check if you have 2SV enabled on your account. If not we set the flag and that’s the end of it. 

Otherwise we check if there’s a previous URL stored in the session. If not we save the current URL. Either way we redirect you to the captive login page of LoginGuard. 

This is also how Joomla’s privacy component works. In fact I invented the captive login technique for Joomla and then Joomla itself copied my technique :)

Regarding your problem it depends on how CB’s plugin works. If it performs the redirect onAfterLogin you have no problem with LoginGuard. If it tries to do the redirection on the page load AFTER logging in it will never work as LoginGuard makes its own redirect and after 2SV redirects you back to the original page you were before. 

As I explained, the same holds true for Joomla’s Privacy component. So if CB’s plugin doesn’t work with LoginGuard it also wouldn’t work with Joomla’s Privacy component, therefore CB would need to make some changes. Maybe ask them how they implement it?

**Comment by rbuelund** [comment]
Hmm.. i got this answer from the CB developers:

> You however should ideally do your redirect after Akeeba LoginGuard has approved the SMS code and completed the login. So whatever Joomla event Akeeba LoginGuard provides for that will be what you use. If Akeeba LoginGuard works like Reset Password or Privacy Consent and stores the redirect destination in session then use a Code action and change the URL in session to wherever you want to redirect them to using PHP. I've no idea what their session variable is so I can't help you with that.

Can I do what they write and change the URL in session to redirect the user ro a certain page after success with the sms token or is that not gonna work ?

**Comment by nikosdion** [comment]
In fact Privacy Consent works exactly like Akeeba LoginGuard. As I said, In invented the captive login technique for Akeeba LoginGuard and Joomla copied it. So, yes, the redirection URL is stored in the session and this is where you're redirected to after going through the Two Step Verification.

The session variable is `com_loginguard.return_url`. I don't know what a code action is, I assume it's something specific to Community Builder. Perhaps if you give them the session variable's name they can guide you from here.

**Comment by rbuelund** [comment]
But what about this:

> So whatever Joomla event Akeeba LoginGuard provides for that will be what you use

I need some trigger to be able to change the redirect URL after tyhe correct SMS token has been entered..

**Comment by rbuelund** [comment]
Code action is a CB plugin where you can choose dofferent CB or Joomla triggers and do different actions upon thoos triggers

**Comment by nikosdion** [comment]
Again, I cannot help you with a CB feature. I can and did tell you what the session variable is and that's it.

There is no event in LoginGuard after Two Step Verification is complete for obvious security reasons.

**Comment by rbuelund** [comment]
Ok - thank you

**Comment by rbuelund** [comment]
I see that you have fixed this after all in 5.0.3 ?? Or now the post redirect from community builder works again 👍

**Comment by nikosdion** [comment]
I am using a different way to capture the redirection URL now. The first URL to be visited after a successful login, before LoginGuard triggers _must_ be one set by the login module / page. So, it will be used as the redirection target. Otherwise the same page which triggered the login will be used as the redirection target as it was the case before.
