### ISSUE TITLE
email tsv will send email even in silent mode

### ISSUE THREAD

**Issue by joomlafun** [akeeba/loginguard#117]
Tested on Joomla 3.10.3  with the latest version of your plugin
Hi,

When the session cookie is still present from the last session and that I enter my credentials I am being directly redirected however I do still receive an email.

Happens both on front-end and back-end

Kind regards,

**Comment by nikosdion** [comment]
It's not a bug. The only realistic solution is to remove the default TSV method feature and have you select a method every time you log in and TSV is required. Having a method as the default means that this method is auto–selected _before_ we can check for the Remember Me feature (it's not called “silent mode”). Remember Me is something that can only be checked after the TSV verification is fully set up which requires selecting a TSV method.

Using a different TSV method which does not send codes to the user as the default works around the feature.

Otherwise, disable the Remember Me feature altogether.

I am tempted to remove Remember Me because people really don't get it. Something to consider for the next version of LoginGuard.

**Comment by joomlafun** [comment]
Hi again,

Thank you for your answer.

I do not know if we understand each other so I'll reclarify step by step : 
1°login with email 2sv, receive a code and check the "remember me"
2°logout from joomla
3°login again with email and be directly redirected to joomla without the "captive view" asking for the email code
4° receive an unwanted email as I will have not to enter the code.

Shouldn't the email trigger  have some sort of conditonnal checking if the user is being, in this case, redirected directly to joomlas back/end front-end?

Kind regards,
