### ISSUE TITLE
0 Class 'Joomla\Plugin\Actionlog\Loginguard\Extension\LoginGuard' not found

### ISSUE THREAD

**Issue by Monrim** [akeeba/loginguard#127]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

Tried to update LoginGuard from 5.0.7 to 6.0.1 today on my Joomla 4 site. I've got Akeeba LoginGuard and Akeeba Backup Pro 9.2.0 installed.

### Expected result

What you believed should have happened following the steps you outlined above.
I expected to just find that LoginGuard had updated itself to 6.0.1 (with no issues)

### Actual result

What actually happened.
Got the error: Class 'Joomla\Plugin\Actionlog\Loginguard\Extension\LoginGuard' not found

Backend:
![image](https://user-images.githubusercontent.com/102662395/160810095-d7d2d700-004f-4548-9898-218fb0601813.png)

Frontend:
![image](https://user-images.githubusercontent.com/102662395/160810376-aae22cde-cd89-4221-89ff-2420e4fc2e99.png)

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.
Tried to uninstall LoginGuard before updating it, but to no avail.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.1.0
* **PHP version**: 7.4.24
* **Am I using HTTPS**: Yes
* **Server Operating System**:Synology NAS - Linux
* **My device's Operating System**: Windows 11
* **My device's Operating System version**: 11
* **Browser**: Chrome
* **Browser version**: Version 99.0.4844.84

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**:10.3.32-MariaDB
* **Server type**: Apache
* **Server version**: 2.4
* **Hosting company / Local server**: Local server - Web Station
* **Server Operating System version**: DSM 7.0.1-42218 Update 3

**Comment by nikosdion** [comment]
Whenever you get a class not found error in Joomla it means that Joomla messed up its cache.

The solution is trivial.

Delete the file administrator/cache/autoload_psr4.php

Joomla will reconstruct this file in the next page load.

Joomla is supposed to do that when you install a new extension. However, sometimes it may fail, e.g. the site may be busy and the operating system might have a write lock on the file when Joomla tries to write to it, failing silently and cocking up your site. Well, I had told them this would happen in 2016. Joomla didn't listen to me. In other shocking news water's wet and Pope's a Catholic...

**Comment by Monrim** [comment]
Thanks for super fast answer.....

However...when I tried your solution it had no effect at all. Still got that:
0 Class 'Joomla\Plugin\Actionlog\Loginguard\Extension\LoginGuard' not found
error :-(

/Monrim

**Comment by nikosdion** [comment]
Is it possible that this plugin was not properly updated by Joomla? Delete the folder plugins/actionlog/loginguard and reinstall the package twice in a row without uninstalling it before or in between.

**Comment by Monrim** [comment]
Hi!

I've deleted the folder you specified, and did one update. This is what happens:

![image](https://user-images.githubusercontent.com/102662395/160827177-8d16b430-2c32-4312-957c-ee40d17fae84.png)

So, i don't even get the chance to make a second reinstall of the package.

/Monrim

**Comment by nikosdion** [comment]
Did you delete the administrator/cache/autoload_psr4.php file again?

If you did that already, your update had completely failed, there's a mishmash of LoginGuard 5 and 6 on your site which is what causes the problem.

In this case you will have to delete the entire plugins/loginguard, plugins/system/loginguard and plugins/user/loginguard directories to regain access to your site. Then you DEFINITELY need to install the package twice in a row without uninstalling it before or in between. This is a Joomla bug when updating extensions I have first reported in 2007. Joomla core maintainers only managed to run into it in February 2022. Still, nobody knows exactly what triggers it which is why it's still unresolved.

**Comment by Monrim** [comment]
Hi!

Well, I deleted all of those directories, and the autoload php file. Then i did a install of LoginGuard 601. This is what happened...

![image](https://user-images.githubusercontent.com/102662395/160831123-c7b61314-6735-493c-858d-15f5ef25ca8c.png)

**Comment by nikosdion** [comment]
Something is really not working on your site. The namespace for the ActionLog plugin is defined in plugins/actionlog/loginguard/loginguard.xml line 19 which reads:

```xml
<namespace path="src">Joomla\Plugin\Actionlog\Loginguard</namespace>
```

If your file DOES NOT contain this line it means that Joomla cannot overwrite it when applying the update to LoginGuard. This is either a file permissions issue or a bug in Joomla itself. We are neither your host nor the Joomla project therefore we can do nothing about either issue. Contact your host and/or the Joomla project.

If the line DOES exist in that file then the problem is that Joomla is not updating its administrator/cache/autoload_psr4.php file. Delete that file.

If you delete that file, you are 100% it is deleted (reload the directory listing!) and the problem persists, open the regenerated administrator/cache/autoload_psr4.php file. It should have a line similar to this:

```php
'Joomla\\Plugin\\Actionlog\\Loginguard\\' => [JPATH_PLUGINS . '/actionlog/loginguard/src'],
```

If this line does not exist it means that Joomla has a bug. Contact the Joomla project.

If this line DOES exist there are two problems which might be happening.

One, Joomla's cache is stuck. Delete all files and folder under `administrator/cache`.

If this didn't help then the problem is with your host. Most likely they are using OPcache with an insanely high revalidation frequency. Contact your host and ask them to invalidate the OPcache on your site. You will have to do that every single time you update Joomla or one of its extensions, i.e. every time the administrator/cache/autoload_psr4.php file needs to be regenerated.

Again, none of these problems have anything to do with our software. It is either a hosting issue or a Joomla issue. I had predicted this kind of issues in 2016 which is when I had warned the Joomla project that using a cache file is a bad idea. A few months after the release of Joomla 4.0 (we're talking about November 2021, more than 5 years after my warning) the Joomla project added a feature to invalidate the OPcache when deleting that cache file but NOT when regenerating it after it's missing. That's why on a server with OPcache and unreasonably long caching settings removing the file won't work. I've tried to explain that multiple times but it's like trying to explain nuclear physics to a deaf dog: a complete waste of time.

Anyway, you now know exactly what's going on and how to troubleshoot it. You will probably bump into this issue again in the future, when more developers stop writing software for Joomla 3 and make their extensions Joomla 4 native. In Joomla 4, unlike Joomla 3, we have namespaces which are cached in the administrator/cache/autoload_psr4.php file with all the problems I mentioned.

For the record, my proposal to Joomla was something much simpler and far more efficient. Since each extension needs to have its namespace cached just add its namespace and path in two extra fields of the `#__extensions` database table. The first thing the application would do is connect to the database and read these fields (a query which takes about 0.005 seconds **at worst**). Instead, they chose to save 0.45 milliseconds per request by doing something that's very prone to breaking in real world sites. Sorry, I tried to tell them repeatedly but they wouldn't believe me because _they do not understand how real world servers work_ and they won't listen to the people who do. If you feel inclined to beat some sense into the Joomla production leadership be my guest. I have expended all the fucks I had to give trying to help them understand why yesterday's releases and the forced authentication method feature they added was disastrous for Joomla and was mathematically leading to people getting locked out of sites. I am too tired to have another long debate about something so obviously wrong they were forewarned and went ahead publishing it broken anyway...

**Comment by kukwm** [comment]
Ok, I have now read and tested this quite a few times. Error remains, although I switched from APC/Opcache to File/Database and deleted the cache before I activated the ActionLog plugin. (By the way what is meant by: "OPcache with an insanely high revalidation frequency“ - the setting for **_opcache.revalidate_freq_** = ?? [mine is 2])

Anyway, disabling the ActionLog plugin does it for now.

What I don't understand in your reasoning (= that issue is due to a general bug in Joomla programming) is the fact that the other extensions that are entered into **autoload_psr4.php** don't have this problem (including your own :) ). The problem would have to appear then nevertheless constantly or not?

Anyway, my thanks for the quick feedback. I appreciate this very much!

**Comment by deltapapa01** [comment]
Hi Nicholas, and thank you for the feedback!
I have exactly the same problem.
I also first deleted the file under administrator/cache/autoload_psr4.php. That was unsuccessful, same error in front and backend.
Then I deleted plugins/actionlog/loginguard folder, after that my site worked again. When trying to update to version 6.0.1, the same error came back.
I then deleted all folders (plugins/loginguard, plugins/system/loginguard, plugins/user/loginguard, plugins/actionlog/loginguard and the file administrator/cache/autoload_psr4.php) and tried to install the extension again. After that, the error came immediately.
The file administrator/cache/autoload_psr4.php, after I deleted it and reinstalled the extension, has the following code on line 118:
`'Joomla\\Plugin\\Actionlog\\Loginguard\\' => [JPATH_PLUGINS . '/actionlog/loginguard/src'],`
The file plugins/actionlog/loginguard/loginguard.xml contains the following code on line 19:
`<namespace path="src">Joomla\Plugin\Actionlog\Loginguard</namespace>`

After I've tested it several times, it can be reproduced every time. I have now deleted the plugins/actionlog/loginguard folder, so at least the page is online.

And now I don't know.

**Comment by nikosdion** [comment]
@kukwm @deltapap01 Can you guys please tell me which operating system your server is using? Are you both on Linux servers? If so, can you please try reproducing this on a Windows or macOS computer and confirm that it doesn't happen?

If this is the case something is really wrong in the way the packages are being built which very likely has to do with Git's problems handling converting a PascalCase filename to a Firstuppercase filename (e.g. FooBar.php to Foobar.php). This is something I had done for all plugin files' Extension classes. If the actionlog plugin's file is being written as plugins/actionlog/loginguard/src/Extension/LoginGuard.php instead of plugins/actionlog/loginguard/src/Extension/Loginguard.php (note the different case in the G of LoginGuard) it would explain why you'd have that problem on Linux which has a case-sensitive filesystem.

**Comment by deltapapa01** [comment]
Hi,
I'm on a Linux server:
Build System: Linux 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Unfortunately, I don't have the option to switch the server to a different operating system.
I could try starting an Xampp server on my windows machine if that helps?

**Comment by nikosdion** [comment]
Try renaming `plugins/actionlog/loginguard/src/Extension/LoginGuard.php` to `plugins/actionlog/loginguard/src/Extension/Loginguard.php`. Note the different letter case in the filename — it should be Loginguard.php (lowercase g) instead of LoginGuard.php (uppercase g). Please tell me if that works for you, folks.

**Comment by deltapapa01** [comment]
I just installed 6.0.1 into a Joomla 4.1.0, and under plugins/actionlog/loginguard/src/Extension/Loginguard.php the file is already called Loginguard.php, i.e. with a small G.
![image](https://user-images.githubusercontent.com/19833064/160889262-a31c0196-8439-4793-b793-dfb029b7b631.png)

**Comment by Monrim** [comment]
Hey! I just updated Joomla to 4.1.2, and installed LoginGuard, renamed the plugins/actionlog/loginguard/src/Extension/Loginguard.php as above (LoginGuard.php) ...and it worked!!

/Monrim

**Comment by kukwm** [comment]
@nikosdion The server with the problems runs with Linux - Joomla 4.2.1, PHP 7.4.24 - It works now with the tip from deltapapa01: renaming the file  Loginguard.php to LoginGuard.php makes the difference.

My dev PC runs with MacOS 12.3. Here I had no such issue.

**Comment by nikosdion** [comment]
@kukwm @Monrim @deltapapa01 Thank you for your feedback! I will address this issue tomorrow — well, later today I guess since it's already 1am where I am — and publish a new release.

**Comment by Monrim** [comment]
Awesome @nikosdion ! Really appreciate all the help and your fast service. Thank you!

Gonna close this issue now.
