### ISSUE TITLE
Joomla 4.2.2 MFA not compatible with Rockettheme Templates / Gantry 5 Front-end Login.

### ISSUE THREAD

**Issue by SpyderZ** [akeeba/loginguard#134]
### Steps to reproduce the issue
- Disabled previous Two-Factor settings & module.
- Upgraded Joomla 4.2.2
- Setup MFA for admin user to use Google Authenticator
- Attempted to log in to the front-end of the website.

### Expected result

- Should have been presented the MFA login after password login to enter the six-digit code.

### Actual result

Forwarded to the home page with the URL as domain_com**/component/users/captive?Itemid=101** and no security box is presented to authenticate. You can't click to navigate anywhere on the site until you clear the cookies. Login fails.

### Troubleshooting already performed

- Installed a fresh Rocket-themed website.
- Updated to Joomla 4.2.2 and set up MFA.
- Tested front end and was successfully able to enter the six-digit code and login fully.

Determined this behavior only happens on **upgraded** web sites and spans multi different Gantry 5 based Rocket templates.

### System information

- Rocky Linux 8.6
- PHP 8.0.3
- Maria DB 10.23.6
- Apache FPM Application
- Cloudflare

#### Mandatory information

Issues without this information can not, and _will not_ be replied to.

* **Joomla! version**: 4.2.2
* **PHP version**: 8.0.3
* **Am I using HTTPS**: Yes
* **Server Operating System**: Rocky Linux 8.6
* **My device's Operating System**: macOS
* **My device's Operating System version**: Monterey
* **Browser**: Brave 
* **Browser version**:1.43.89

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: Maria DB 10.23.6
* **Server type**: Apache, Nginx (proxy)
* **Server version**: 2.4.6
* **Hosting company / Local server**: Digital Ocean / Plesk
* **Server Operating System version**:  Rocky Linux
### Additional comments

Joomla Bug Report: [https://issues.joomla.org/tracker/joomla-cms/38678](https://issues.joomla.org/tracker/joomla-cms/38678)
Gantry 5 Bug Report: [https://github.com/gantry/gantry5/issues/3078](https://github.com/gantry/gantry5/issues/3078)

**Comment by nikosdion** [comment]
Please do not submit issues about Joomla core features in this repository. Submit them to Joomla's GitHub repository's Issues page: http://github.com/joomla/joomla-cms/issues/new

That said, your problem is actually a problem with how Gantry implements their index.php. Their option to hide the component output from the Home page is incompatible with Joomla 4, plain and simple.

This option is a non-standard approach which will not work with any extension, core or third party, on Joomla 4 when they need to display a page without having a menu item set up explicitly for it. As RocketTheme **should** have known had they actually been responsible software developers and tested Joomla 4 anytime the last 6 years i.e. since its Alpha 2 in November 2017, while Joomla 3 never added an Itemid to direct component URLs which do not use a menu item (e.g. `index.php?option=com_example&view=something`), Joomla 4 **always** adds the menu item ID of the Home menu item. Since they only simple-mindedly check the Itemid in the URL (instead of making sure it's _also_ the same component, view and task at the very least) they are hiding the component output of all these URLs, breaking core and third party extensions.

Their non-standard, problematic approach breaks among other things Akeeba Backup's legacy front-end backup and JSON API URLs, Admin Tools' custom error page, Akeeba Ticket System's canned replies, Akeeba Engage's comment box on a new page (behind a confirmation link) and comment edit page, even Joomla's login page if you only publish a login module but not a login menu item on your site — just to name a few legitimate use cases of Joomla's ability to work with direct component URLs which do not require a menu item to be set up in the frontend.

This is something RocketTheme needs to fix. The fix is trivial — about 100 characters. Any developer reading this reply knows what to do.
