### ISSUE TITLE
Test Report

### ISSUE THREAD

**Issue by brianteeman** [akeeba/loginguard#15]
- [x] Installed and configured 
- [x] Added yubikey to super user
- [x] tested yubikey and emergency code in the admin for super user
- [x] tested yubikey and emergency code in the front end for super user
- [x] create a new regisatered user without any tsv
- [x] logged in as new user was prompted to add tsv
- [x] added yubikey to new user
- [x] logged in as new user and was able to successfully use the yubikey and emergency codes as tsv

Not quite sure what the geo-ip plugin was needed for
two language string typos submitted

**Comment by nikosdion** [comment]
The GeoIP plugin is used on the Second Step page (where it lists all the methods). If you use a public IP address instead of localhost _and_ have the GeoIP plugin installed it will tell you which country and city you last used that method from. Just like Google does ;)

Thanks for the typos!

PS: I'm closing this issue. If your tests reveal any issues feel free to reopen it.
