### ISSUE TITLE
View not found [name, type, prefix]: loginguard, html, loginguardView

### ISSUE THREAD

**Issue by PhilETaylor** [akeeba/loginguard#23]
Install loginguard
install Geoip plugin

Click this upgrade button:

<img width="429" alt="screen shot 2017-03-12 at 18 00 53" src="https://cloud.githubusercontent.com/assets/400092/23834401/dd1a909e-074d-11e7-8085-a1e58da49f0b.png">

gets to http://example.com/administrator/index.php?option=com_loginguard&task=welcome.upgradegeoip&s3R4DfolyAymifVkgObOY5hDsw6haxKp=1

with error page:

<img width="694" alt="screen shot 2017-03-12 at 18 01 24" src="https://cloud.githubusercontent.com/assets/400092/23834405/ee4d8074-074d-11e7-9e2e-58bf08c83c66.png">

[systeminfo-2017-03-12T17-59-27.00-00.txt](https://github.com/akeeba/loginguard/files/836770/systeminfo-2017-03-12T17-59-27.00-00.txt)

**Comment by PhilETaylor** [comment]
Opps...... :-( 

<img width="633" alt="screen shot 2017-03-12 at 18 48 22" src="https://cloud.githubusercontent.com/assets/400092/23834817/7f6c3af4-0754-11e7-8f57-2a65e3b4878a.png">

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/14550

Can be closed once that's merged.

**Comment by nikosdion** [comment]
I guess I will close this as wontfix because, er, it's a Joomla bug. Sigh...

Can we torch the damn code base and bloody get that 4.0 out the door before we die from old age?

**Comment by nikosdion** [comment]
Seeing what @mbabker tried to do in Joomla! 3.7 I understand why this broke. While a great idea on paper, trying to have the MVC classes go through the autoloader bumps on the same obstacle I discovered in 2011 when I started writing FOF 1.0: you have the same class names in the front- and backend. As a result you have the same class name in two different paths on the same code base. If you want to be DRY you will try to inherit one from the other. No can do :(

The only way to do this is what Michael already hypothesized in joomla/joomla-cms#14550 : full namespace support in the MVC. This is what I did with FOF 3.

Well, technically there is another solution as well. Pay attention, I'll tell you how to fix Joomla's architecture without breaking b/c and without having developers come after you with torches and pitchforks. This is what I was trying to say back in July 2015 but the self-absorbed professors wanted to reinvent Symfony and Laravel... But I digress.

You can add a Site or Admin prefix to the MVC classes. Therefore FoobarModelBaz would become AdminFoobarModelBaz for the backend and SiteFoobarModelBaz for the frontend. The site part (admin or site) can be passed as a $config parameter in JControllerLegacy, JModelLegacy and JViewLegacy. If none is set discover it through JApplication.

The class autoloader only looks for the prefixed class. The Legacy classes, if they fail to load the prefixed class, can revert to the old class names and require_once method. This way:

* Existing components work.
* You can migrate all old components to the stopgap architecture.

In the next architecture iteration (4.0) you look for a namespaced class \Site\Foobar\Model\Baz and the old style prefixed class SiteFoobarModelBaz - but you drop support for the ancient FoobarModelBaz name. At the same time you introduce a component PSR-4 autoloader which is registered automatically when you start including a component (and which can be called independently by a module or plugin which needs to use the component's classes). This way:

* Migrated components still work (your software works on 3.x and 4.x)
* You can migrate components to a *proper* namespaced, PSR-4 architecture that uses the folders View, Controller, Model, Helper instead of the legacy views, controllers, models, helpers.
* **Risk**: if you update a site with non-migrated components it will break.

In the next architecture iteration (5.0) you drop support for everything except PSR-4. Therefore:

* Migrated components still work (your software works on 4.x and 5.x)
* We have fixed the namespacing issue without anyone's software or site breaking.
* **Risk**: if you update a site with non-migrated components it will break.

If you want to mitigate the risks you can implement the PSR-4 autoloader in 3.x, do not implement the stopgap architecture and not drop support for the ancient style class names until 5.0. IMHO that's a bit harder to do but whatever floats your boat.

Anyway. If you have a roadmap it's EASY to implement namespaces and make big architecture changes without breaking shit. As always, Joomla's problem is that nobody has the balls to set a bloody roadmap.
