### ISSUE TITLE
Force to use Two Step Verification

### ISSUE THREAD

**Issue by mariottide** [akeeba/loginguard#27]
Is it possible to force the Two Step Verification at the first log in?

**Comment by nikosdion** [comment]
Check [the options of the User plugin](https://github.com/akeeba/loginguard/wiki/The-user-plugin). Please note that with this option you cannot force people to enable Two Step Verification. Do you just want to inform the users and let them enable TSV if they want to (already supported) or force them to use Two Step Verification to use the site at all? If it's the latter, what is the use case? It can be implemented, I just couldn't see a valid use case for it.

**Comment by mariottide** [comment]
I want force the users to enable TSV. It may be useful in websites that sell courses. With TSV the user can not share its username and password with other people.

**Comment by nikosdion** [comment]
Actually I can't implement that. Right now we allow redirections to any URL after logging in if the user does not yet have TSV enabled. If we are trying to *force* TSV we have to always redirect to a com_loginguard page. Otherwise we'd end up with an infinite redirect loop. Removing a useful feature (redirect to a custom page which explains the benefits of TSV) over a questionable feature (force TSV) doesn't sound like a good trade-off.

Moreover, I see that your use case is actually invalid. TSV will not prevent anyone from sharing their login. They can simply share their Google Authenticator code. Or they can set up multiple U2F security keys or YubiKeys, one per person. Or they can simply call each other... Two Step Verification is about increasing the account's security for the user, not for the site owner. It makes sure that if you are not the user, i.e. you do not have the second factor, you cannot log in. This is meant to prevent unwanted impersonation. Nothing in TSV prevents you from willingly allowing someone you know impersonate you on the site.
