### ISSUE TITLE
U2F Yubikey does not work in Chrome 60

### ISSUE THREAD

**Issue by cheiff** [akeeba/loginguard#34]
### Steps to reproduce the issue
- Introduce the U2F key in the USB
- Install LoginGuard plugin
- Activate the U2F plugin
- Components/Akeeba LoginGuard
- Security Key -> click "Add a new security key"
- Click Register your Security Key

### Expected result
- Browser prompts for key button press

### Actual result
- Browser prompts with this message:
"The U2F key registration cannot be processed. Please make sure you are using a publicly accessible domain name for your site, not one defined locally e.g. in your hosts file, MAMP and so on."

### System information (as much as possible)
* **Joomla! version**: 3.7.5 Clean install
* **Database type**: MySQL
* **Database version**: 5.7
* **Server type**: Nginx
* **Server version**: 
* **Hosting company / Local server**: DigitalOcean
* **Am I using HTTPS**: No
* **Server Operating System**: Ubuntu 
* **Server Operating System version**: 16.04
* **Browser**: Chrome
* **Browser version**: 60.0.3112.101-1

### Additional comments

- The site is publicly accessible
- The Yubikey demo site https://demo.yubico.com/u2f works perfectly with that Yubikey and browser
- The same Joomla instance with firefox 54 and the addon "U2F Support addon" works perfectly.

**Comment by nikosdion** [comment]
Not reproducible. I can say that for sure since I'm using Chrome on a daily basis, on all three major OS, with a YubiKey, on all of my live and development sites. As the message reads, Please make sure you are using a publicly accessible domain name for your site, not one defined locally e.g. in your hosts file, MAMP and so on. Moreover **keep  in mind that ONLY HTTPS sites with a valid, commercially signed and TRUSTED SSL certificate will work with U2F**. If you have an SSL certificate by StartSSL, Symantec or any other vendor which got downgraded to "untrusted" by Google in Chrome 60 there's your problem.

**Comment by cheiff** [comment]
Hi,
as explained, I am not using SSL and exactly the same site in firefox works fine.
I forgot to add that I am using Chrome in Ubuntu 16.04 desktop.

**Comment by nikosdion** [comment]
Again, **THIS IS NOT A BUG** and it's documented. The U2F specification *requires* HTTPS. The third party Firefox implementation violates this specification and allows you to use it over plain HTTP. Also note that you are talking about how *the browser itself* implements  U2F.

Since it's not an issue, fully documented and you keep wasting my time with this non-issue I am locking the thread.
