### ISSUE TITLE
Feature change styling/ appearance 

### ISSUE THREAD

**Issue by lenusch** [akeeba/loginguard#36]
Hi, 
would it be possible to add own CSS and have options like "deaktivate topbar" and center 2FA Mask and so on, upload Logo from Company... 
This would be great.

**Comment by nikosdion** [comment]
This is already possible using standard Joomla! template overrides. Please consult our [documentation wiki](https://github.com/akeeba/loginguard/wiki), especially the pages:

* https://github.com/akeeba/loginguard/wiki/Customizing-the-frontend-display
* https://github.com/akeeba/loginguard/wiki/Customizing-the-backend-display

Please note that template overrides is a feature available in Joomla! since version 1.5 released in 2007, ten years ago. All properly written Joomla! components support them. There is nothing extraordinary or novel about them.

Since what you are requesting has been implemented by Joomla! ten years ago I am going to close this issue as 'invalid' :)
