### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by fede91it** [akeeba/loginguard#39]
I see that the plugin doesn't have translations.

If you could extract the strings in English I'm ready to translate it into Italian

**Comment by nikosdion** [comment]
As noted [on our download page](https://github.com/akeeba/loginguard/releases) we have language files - or at least the infrastructure to provide them:

> Akeeba LoginGuard comes with English (Great Britain) language built-in. Installation packages for other languages are available [on our language download page](https://cdn.akeebabackup.com/language/loginguard/index.html).

The problem is that not many people are interested in actually translating this software. If you want to contribute to the Italian translation of the component please create an account on our [translation platform](https://translate.akeeba.com/) and reply here with your username. I will then give you translator privileges :)

**Comment by fede91it** [comment]
Great!

fede91it

**Comment by nikosdion** [comment]
Hello Federico,

I have now added you as a translator. Thank you!

**Comment by fede91it** [comment]
Thanks

**Comment by fede91it** [comment]
Activaction token expired, please resend

**Comment by nikosdion** [comment]
The site does not read GitHub and does not understand English. Try interacting with it on a browser.
