### ISSUE TITLE
i Dont see the Overview Page

### ISSUE THREAD

**Issue by johanpeters** [akeeba/loginguard#46]
i have v2.01 installed.. latest version of joomla (3.8.7).

package installed.. 2FA works.. but i dont have a overview page to manage 2FA..
in component i have Akeeba LoginGuard. but only for myself.. not general..

**Comment by nikosdion** [comment]
Works as documented. Your feature request is declined. Please read the fine wiki.

**Comment by johanpeters** [comment]
I have read the wiki.. but I don’t see the features on the backend.. 
Only data I see is settings for me as user.. not for al other users..

**Comment by johanpeters** [comment]
I don’t see

System check

This page performs a number of self-checks:

Is the system plugin enabled? Without it the Two Step Verification system does not have any effect.
Are there any installed and published Two Step Verification method plugins? Without any active plugins the system has no effect.
Is the user plugin enabled? It is required to edit other users' Two Step Verification preferences.
Is the optional GeoIP plugin enabled and published?
If an issue is detected with any of the above checks you will be notified and given instructions to resolve them.



Managing Two Step Verification

At the bottom of the page there are two links to manage Two Step Verification for your account or for all user accounts. Please note that for security reasons you cannot edit the Two Step Verification options for other Super Users on your site.

**Comment by nikosdion** [comment]
Where in the wiki did you read this feature that I explicitly did not want to implement exists?!

Go to Users, Manage, edit a user and see the Two Step Verification tab. As long as the user plugin is enabled of course. 

There is no overview page because Joomla lacks the features necessary to add information in the overview users view. Implementing our own overview page requires time which I don’t have. So this is a very “maybe in the not so immediate future” kind of feature.

**Comment by johanpeters** [comment]
Hello,

https://github.com/akeeba/loginguard/wiki/The-backend-overview-page <https://github.com/akeeba/loginguard/wiki/The-backend-overview-page>

**Comment by nikosdion** [comment]
Facepalm. OK, I see that the problem is you didn’t read the wiki or my reply. You skimmed through it. Have a lovely day.
