### ISSUE TITLE
Webauthn\FIDO2 support

### ISSUE THREAD

**Issue by Vednier** [akeeba/loginguard#67]
U2F support was disabled for "unsupported" browsers in issue #66. But its, actually not important because U2F already superseded by Webauthn\FIDO2 which, according to https://caniuse.com/#search=webauthn is way better supported among browsers. Firefox supports it, natively and by default for almost year, Chrome came little later and recently Microsoft Edge started to support it too. Even Apple testing it.
FIDO2 devices already present on market and U2F dongles is supported by Webauthn too. Maybe its time to replace never-properly-supported U2F with standardized WebAuthn?

**Comment by nikosdion** [comment]
No, you are wrong. Now that I had more coffee I can expand further than I did on #66.

First of all, Webauthn stands for [W3C Web Authentication](https://www.w3.org/TR/webauthn/) standard. It is a standard for _authentication_, not two step verification. On the other hand, U2F (Universal Second Factor) is a second factor, i.e. a two step verification method. One does not replace the other.

If you read FIDO's site, their goal is to make authenticating to web applications secure and easy. The first step was to address the most common login security method, two step verification and two factor authentication. In the traditional model you have an application or hardware device generate a 6 to 12 digit code every few seconds or, worse, send that code over SMS, email, push notifications etc. The security issue lies on the fact that a. the secret used to generate the code or the code itself can be intercepted and b. the user needs to type in information which can be intercepted. Using a hardware token with a security hardened cryptographic processor steps over these limitations. The only information over the wire is a challenge and a response. Furthermore, the browser verifies (by means of TLS certificates) that the site posing the challenge matches the site of the cryptographic certificate sent to the hardware token.

The next step is to get rid of usernames, passwords _and_ two step verification altogether. This is what FIDO2 / Webauthn is designed to do. Cryptographic challenges are used to authenticate you to a website, replacing your username and password. These challenges can be bound to biometric identification (e.g. Windows Hello) or a PIN, thereby offering multi-factor authentication that's easier for the user to manage: they only need to remember a PIN. If that sounds familiar it's because the concept is not new. It's been used in enterprise, government and military applications (see: PIV). Webauthn takes those concepts, modernizes them and puts them in the browsers. However, Webauthn is authentication, not second factor.

U2F (FIDO) dongles **do not** support Webauthn. FIDO2 dongles **do** support both Webauthn _and_ U2F. That is to say FIDO dongles are NOT forwards compatible, despite your false assertion. FIDO2 dongles ARE backwards compatible with FIDO U2F. You might be confused because FIDO2 / Webauthn is an extension to U2F. Yes, it's an extension. Old dongles don't speak the extension API. That's why they do not work with FIDO2 / Webauthn.

Regarding browser support of U2F, you are wrong. It's not removed from any browser and there are no plans to have it removed. The only problem is that only the Chromium engine supports it. This limits support to Chrome, Chromium, Opera, future versions of Edge and other Chromium-derived browsers. It's also kludgy on mobile devices since it's only supported on Chrome (and Opera) on Android using Google Authenticator as the middle man and only if you have an NFC-enabled U2F dongle. Finally, U2F support will not be added to other browsers but Webauthn support has.

Regarding Webauthn, yes, the API was there for the better part of a year in all major browsers BUT there was no hardware to support it until around May last year (as far as I can recall; I didn't spend time checking this but I remember that I could only get FIDO2 dongles around Summer last year). Webauthn is still not supported in Safari and iOS in general.

But this is all nonsense in the context of LoginGuard because Webauthn is authentication, not second factor. If you want to implement two step verification with a FIDO2 token you need to use their support for the older FIDO U2F standard which is something that's already implemented.

Webauthn is something that does not belong in LoginGuard. LoginGuard is two step verification. It's not authentication. It would have made more sense in SocialLogin and, in fact, it's something [I actually tried implementing](https://github.com/akeeba/sociallogin/issues/17). The results were not very promising at that time (December 2017). The biggest challenge was that authentication was bound to a specific browser and biometric/dongle per user account and site. This requires a management interface for authentication which becomes rather gnarly without native support from Joomla! itself. I also ended up discontinuing SocialLogin.

If at some point someone does offer a Webauthn integration for Joomla! and you do use it as your preferred authentication method you will no longer need to use LoginGuard or any other second factor method for that user account. That's the whole point of Webauthn: to eliminate two step verification as a separate task to logging into a site.

So this issue will be closed as out of scope. Please do read the information about these two technologies and don't make assumptions and assertions that are not grounded in reality. Some of us actually own the hardware and have already worked on the integration, understanding the differences and the challenges. Maybe it's time for users making feature requests to do their homework instead of asking poorly thought out questions? ;)

**Comment by nikosdion** [comment]
I apologize because I was very wrong about Webauthn compatibility. Contrary to the original material sent by Yubico several months ago and the original Microsoft Edge implementation the current Webauthn standard **is** compatible with the old U2F keys. You were mostly right. The real difference is that the old U2F (FIDO) keys only confirm user presence which means that you still need to supply a username to get the user's identity. The new FIDO2 keys, or using a Trusted Platform Module (TPM), also provide user identity --as far as I can tell, I am still waiting to receive my FIDO2 key-- making the username redundant.

### What does that mean in practical terms?

It's still not a valid Two Step Verification method, it's an _authentication_ method. In fact, logging in with Webauthn would definitely make LoginGuard redundant. Between my previous reply and this I resolved a bug in LoginGuard which **does** allow skipping its 2SV depending on the login method used.

### How would Webauthn be implemented?

This is the complicated bit, since we need to support both legacy (FIDO) and modern (FIDO2, U2F) authenticators.

For starters, this requires a special login module. The approach used by LoginGuard requires Joomla to perform the authorization before getting somewhere that allows us to handle further actions, making it unsuitable for an authorization method like Webauthn. The approach used by Social Login assumes that the whole identity is provided by the authenticator. This would work with FIDO2 keys and TPM but not with U2F keys. So that's not good either. We need a special module which offers the option of either entering a username or using Webauthn.

Next up, we need plugins to handle storing / retrieving the credentials (ID and public key), authorization and providing a user interface for adding and removing authenticators. In theory that's three plugins but I have already established that they can all be rolled into a single system plugin. Out of sheer necessity that would have to work in conjunction with the login module.

The other problem is that Joomla provides a login page through com_users. I _could_ try to inject another field into the frontend form through the system plugin I mentioned above. I would still need to see if that works well or if I would need to ask you to make a template override and insert some custom code. Most likely it'd be the latter.

Backend login is also complicated for the same reason (it's handled by a _different_ login module than the frontend login). Injecting buttons there is very template specific so probably you'd need to swap it out with a special module written for this purpose.

With all that in mind we have two modules and a plugin -- and maybe some template overrides. It starts sounding an awful lot like a completely different solution than either LoginGuard or Social Login. I think this is the route that I'll follow for this, a separate package. I can't give an ETA **but** I will be working on it.

**Comment by Vednier** [comment]
Just several more cents to subject.
1) Yes, FIDO2 WebAuthn and U2F is different in terms that U2F keys can be only used for second factor, not as "passwordless" solution, but personally i dont see much use of paswordless auth anyway (its only my opinion) and if WebAuthn allows strong second factor with hardware key - why not? Considering fact how much u2f keys already exists in willd, especially.

2) I closely monitor how Firefox devs works in Webauthn area and i can certainly say that they absolutely dont rush in CTAP2 (actual FIDO2 keys) support implementation. Just for hint they taken several years just to start working on U2F and Firefox ONLY supports CTAP1(U2F) right now and for foresee future.

But, for example, U2F key + WebAuthn works perfectly on Dropbox.

Anyway, i posted this bug simply because so far its kind of egg and checken issue - there is a lot of talks but almost no real world WebAuthn implementation in web, so its not much of point into getting keys and vice versa.

**Comment by nikosdion** [comment]
Well. I wrote a WebAuthn passwordless login implementation for Joomla. It supports both FIDO U2F and FIDO2 CTAP2 keys. I tested it with Chrome, Opera and Firefox on Linux and macOS. Also on Android with NFC. They work just fine. I don’t know why you think there’s no usable WebAuthn implementation. Safari beta versions implement it as well. Edge implemented it first, it’s actually a Microsoft thing that became a standard. 

Yes, right now they don’t implement authentication without sending a list of valid certificates which means that the flow is awkward: enter your username, click a button, interact with the hardware key. Still this is far more convenient and secure than using a password manager. 

Yes, this means that right now these are all U2F implementations under a different name. They seem to work better than U2F though. With straight up U2F I have all these issues with registering a key on browser A and it not working on browser B for some stupid reason. Maybe I’ll try WebAuthn for 2SV but I’m reluctant mostly because it doubles the package size with all the third party requirements it needs to pull in.
