### ISSUE TITLE
Problem with akeeba login guard, when regenerates backup codes return to error 403 access forbidden

### ISSUE THREAD

**Issue by gomiemeru** [akeeba/loginguard#68]
### Steps to reproduce the issue

1. I am using free joomla template named "astroid" from joomdev that can be download from here:
https://www.joomdev.com/blog/entry/astroid-template-framework
2. I installed Akeeba LoginGuard (pkg_loginguard-3.0.4.zip)
3. Everything works fine, but there's only 1 problem. When I use "Backup Codes (Emergency Access)" setting, and when I press "regenerate backup codes", it returns to this error:

An error has occurred.
403 Access forbidden. 
Return to control panel

I am using PHP 5.6 but even after I changed to PHP 7.0, 7.1, 7.2 or 7.3 the problem is still the same. It cannot "regenerate backup codes" the error still the same (403 access forbidden).

The joomla itself still clean quickstart full version from what i downloaded from https://github.com/joomdev/Astroid-Framework/releases/tag/v2.1.0

astroid-framework-v2.1.0-j3.9.4-quickstart.zip

I don't install any other plugin except from akeeba. 
My access is as Super Users, so I don't have any limitation to any access.

Please help. It is the only problem I have with Akeeba LoginGuard (which is cannot REGENERATE BACKUP CODES")

Thanks for you answer

**Comment by nikosdion** [comment]
This will only happen if the session token sent to the server does not match the current session token. The only way I can imagine this being possible is that there's full page caching enabled on your site or a third party plugin is killing off part of the request.

Make a test without caching first. Go to Global Configuration and set Caching to None. Make sure the "System - Page cache" plugin is disabled. Also make sure that you are not using a caching CDN (such as CloudFlare) or a server-level caching (e.g. SiteGround's SuperCache, LiteSpeed Cache or any other caching option provided by your host or a third party plugin). If the problem goes away then the issue is with caching. In this case I can do nothing about it since we're _already_ telling Joomla NOT to cache the page. Incidentally that also causes Joomla to emit the correct HTTP headers to prevent caching. Therefore that would be a bug in a third party caching implementation.

If the problem persists it means that a third party plugin is screwing something up, either by regenerating the session token before LoginGuard can process it (which is stupid and breaks Joomla) or by corrupting the request (which is also stupid and breaks Joomla). I've had some experience debugging issues like that and the only solution is to find which third party extension breaks how Joomla works and complain to its developer.

**Comment by gomiemeru** [comment]
- I have disabled cache (Global config - system - cache setting - system cache set to OFF, caching disabled)
- Cleared cache (clear cache and expired cache)
- disable plugin (system - page cache)
- I'm not using CDN or any server level caching


All with no luck, it still gives me 403 Access forbidden when i press regenerate backup codes.

Well, this case is not an emergency things, google authenticator still works fine. But right now regenerate backup codes still UNSOLVED for me. I'll update if i found the problem and how to fix it someday. 

Right now let's wait if any other LoginGuard user face the same thing as me. 
Btw I like this plugin, really helpful. Thank's for creating very useful plugin Dion :)

**Comment by nikosdion** [comment]
This issue cannot be reproduced on any of my development, test or live sites and has not been reported in over a month by anyone else using this software. Considering that we are not doing anything special during backup code regeneration (it's a run of the mill request), i.e. we are using very basic core Joomla functionality, this is not something that can be considered as a bug in our software. To me, it's pretty clear that this issue comes from some third party plugin or your server configuration, both outside our control and scope.

Unfortunately, we cannot provide personalized support for issues affecting just your own site but cannot be reproduced and have not been reported by anyone else in a reasonable amount of time. Therefore this issue will be closed with the "invalid" label.

Please note that if in the future you find instructions which allow this issue to be reproduced on different sites, **on different servers**, please file a new ticket with instructions to reproduce the issue. Kindly remember that if the issue cannot be reproduced on more than one sites _and_ servers it is not a bug, it's a site or server configuration issue and we cannot help.

Thank you for your time and have a great day!

**Comment by paolo-tateo** [comment]
I have the same problem. Did you solve it?
Thank you very mutch

**Comment by nikosdion** [comment]
I cannot reproduce this issue. As I explained a couple of months ago, this would only make sense if you have a caching issue.

Our software tells **Joomla** not to cache the page. The core Joomla caching code respects this and does not cache the page. Moreover, the core Joomla code generates HTTP headers which tells standards-compliant CDNs, caching proxies etc which sit between your web server software and your visitor to NOT cache this page. We cannot guarantee that _third party software_ will respect this standard Joomla behaviour. I have seen enough third party extensions which treat all public pages as something to cache, despite the component saying otherwise. If you have something like that then the problem lies with that third party extension.

As I said two months ago you need to try reproducing this issue on a new site, on a different server. If you try that on a freshly installed Joomla site you will see it's not possible. Install your third party extensions one by one until you can reproduce your issue and you'll know which one is causing it. If you still cannot reproduce this issue something is wrong with your original site setup, either at the hosting side (some hosts _do use_ caching proxies, e.g. SiteGround calls it SuperCache when it's in fact just a Varnish cache with very aggressive caching options which break core Joomla features and LoginGuard and several third party extensions) or because of a CDN you put in from of your site (check its configuration).

Whenever you have an invalid token issue with ANY extension, third party or core Joomla, these are the troubleshooting steps you need to follow.

**Comment by paolo-tateo** [comment]
I just installed a fresh Joomla 3.9.28 (without any additional extension) on the same server (CentOS 7, panel CWP, managed by my team)
The server does not manage any cache service, and I found the same problem, both in the front end and backend.
I tried with PHP 7.3 and PHP 7.4

The only clue I have found into log is this: (akeeba is the user of the server where I installed the test website)

[Sun Jul 11 16:59:28.792551 2021] [proxy_fcgi:error] [pid 28361:tid 140453626218240] [client 179.43.169.181:49976] AH01071: Got error 'PHP message: PHP Warning: require_once(/home/akeeba/public_html/libraries/import.legacy.php): failed to open stream: No such file or directory in /home/akeeba/public_html/includes/framework.php on line 17PHP message: PHP Fatal error: require_once(): Failed opening required '/home/akeeba/public_html/libraries/import.legacy.php' (include_path='.:/opt/alt/php-fpm73/usr/lib/php') in /home/akeeba/public_html/includes/framework.php on line 17'

**Comment by nikosdion** [comment]
I saw this reply and your ticket.

As luck would have it, this week we were left without childcare on a few hours’ notice. This limits my availability severely.

On top of that, it would not make any sense for me to debug this version of LoginGuard on your server or any server. Last month I rewrote LoginGuard from the ground up. Debugging the old version would be a waste of time.

I will publish a dev release of the new version as soon as I can. To compound what was already a fraught situation, we got a power outage which means I can’t use my desktop to publish a dev release.

**Comment by paolo-tateo** [comment]
The new version is good news! 
Do you have a prediction on the time of publication? Days or weeks?
Thank you very much

**Comment by nikosdion** [comment]
Developer's release: https://www.akeeba.com/download/developer-releases/loginguard-dev/revff94aca.html

Please install this and see if it addresses the issue you were having.

I had originally planned to release this tomorrow. However, given that we're left without childcare I won't chance a release this week. Next week I have Monday and Tuesday blocked which leaves us with July 21st as the most likely release date.

**Comment by paolo-tateo** [comment]
Thank you!
