### ISSUE TITLE
Second Security Key

### ISSUE THREAD

**Issue by Ann-Sophie81** [akeeba/loginguard#73]
Hello

I have a Problem with the 2 step login. I registered two Security Keys (SoloKey).
There is no problem with registration. The first i named SoloBlack and the Second SoloRed.
Solo Red ist my Backup Key. I use normaly only the Black Key.

The problem is that i can not login with both keys. I can only login with the latest registered. So my backup key is not working when i registered it first. Only the key witch is registered at latest function with the login.

Is there a workaround to use both keys?

Thanks an sorry for my poor englisch

Regards
Ann-Sophie

**Comment by nikosdion** [comment]
I need some more information since I cannot reproduce your issue.

Are we talking about U2F or WebAuthn?

Is your security key compatible with FIDO or FIDO2? Please specify.

Which browser (make and version) and which operating system (make and version) are you using when setting up and when trying to use the keys? 

There's a reason I am asking. For example, U2F security keys set up with Chrome don't work when you try using them with Firefox and vice versa. That's due to incompatible implementations of U2F on each browser and no, there's nothing we can do about it. U2F was a great idea but all browsers except Chrome and Chrome-based ones either half-assed it or didn't support it at all. Using WebAuthn solves this problem and it's at least a standard that all browsers aim to support in the future thanks to it being a _W3C_ standard, not just a FIDO standard.

**Comment by Ann-Sophie81** [comment]
Hi!

Sorry, i was long month in hospital.

I am using Solokeys from Solokeys.com. I have the Model Solo USB-A and Somu and Solo Tap USB-A and also Solo USB-C in use.

I am using Chrome actually Version 79.0.3945.130 (Offizieller Build) (64-Bit) and Windows 10 1909 Build 18363.592 on diffrent Hardware.

Yes i use U2F. The thing is i can regsiter more Solo Keys but login is only with the last registrated possible. Is it possible to use two ore more keys with webauth? I can not register a second one...

Thanks
Ann-Sophie

**Comment by nikosdion** [comment]
Sorry to hear that.

Using multiple U2F keys has been supported since the very fist version. I have tested with multiple keys but not for a long time. I have also not changed that code for the same amount of time.

That said, browsers have deprecated U2F since May 2019. It is time to migrate to WebAuthn instead. It definitely supports multiple keys. All of my development and production sites use LoginGuard with WebAuthn and a mix of OS and browsers (I have used all major browser on all major desktop and mobile platforms). Even your old FIDO keys will work with WebAuthn just fine.

**Comment by Ann-Sophie81** [comment]
Hi!

I am just changing all logins to webauth and it works fine with different keys. But is this normal? I login with my user name and password and then I have to put the button on key and than put in the pin code and again put the button on the key? This is login in 4 steps or do I something wrong?

Thanks

**Comment by nikosdion** [comment]
The expected result is that you log in with your username and password, then your browser implements the platform-specific security key interaction.

Windows allows you to **optionally** protect the use of your security key with a PIN code. So, yeah, in this case you also have the PIN interaction. That's an optional feature you enabled on Windows to make using the security key even more secure.

**Comment by Ann-Sophie81** [comment]
Sorry its not your businesses... but where can I disable this pin function for security keys?

**Comment by nikosdion** [comment]
I'm at a conference and don't have access to my Windows desktop. I found a [tutorial on Security Key PINs](https://www.tenforums.com/tutorials/123274-change-security-key-pin-log-into-apps-windows-10-a.html) which seems to be correct, if my memory serves. I hope that helps!
