### ISSUE TITLE
Redirect loop when user has password reset required and force 2FA

### ISSUE THREAD

**Issue by davidjosephhayes** [akeeba/loginguard#76]
### Steps to reproduce the issue

Flag a user as "Password reset required" and place them in a group with 2FA required. Attempt to login as this user.

### Expected result

Either profile page is displayed with option to reset password, then redirected to 2FA auth/setup or vice-versa

### Actual result

Redirect loop.

### Troubleshooting already performed

Toggling different setting.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 7.9.13
* **PHP version**: 7.3
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: Ubuntu
* **Browser**: Chrome
* **Browser version**: newest

**Comment by nikosdion** [comment]
Related to https://github.com/akeeba/com_datacompliance/issues/28

It seems like Joomla has changed something lately because I remember having tested LoginGuard and DataCompliance (which copied code from LoginGuard) with forced password reset a while ago.

**Comment by davidjosephhayes** [comment]
I saw the comment related to the privacy policy plugin in the code when I was poking around to see if there was an easy fix. 
😂 https://github.com/akeeba/loginguard/blob/2768bfcc7641d73937d1f93cf9a66a26c996a386/plugins/system/loginguard/loginguard.php#L118

**Comment by davidjosephhayes** [comment]
Functionally, should the password reset or the 2FA happen first?

**Comment by nikosdion** [comment]
2FA is part of Joomla. It happens with the login so it precedes the forced password reset.

LoginGuard implements 2SV and it comes after logging in. Because Joomla issues a redirection in a way that cannot be caught we have a redirection loop.

The way it will work is that you will be able to reset the password without being displayed the 2SV captive page BUT after the password reset you will still need to provide your 2SV to access the site.

Even if someone fools a Super User to force password reset to your account AND they have access to your email to complete the password reset they will STILL be unable to access your account – the entire point of having 2SV enabled in your account.

I am not worried about the security aspect of this. It's already covered.

**Comment by nikosdion** [comment]
I stand corrected. Joomla is a rolling dumpster fire. The forced password reset redirects you to the user profile edit page. This would allow turning off Two Step Verification (LoginGuard) and Two Factor Authentication (Joomla). Considering that forced password reset is primarily used in situations we expect the user credentials to have been compromised, the implementation of that feature in Joomla undermines security even further. It's an anti-feature.

I will have to work around this somehow. If I can't, I will simply not address it because in my humble opinion it is better to have an infinite redirection loop than a hacked site. The infinite redirection loop is easy to fix; unset the forced password reset and give the user the link to the password reset page.

**Comment by nikosdion** [comment]
I had to be sneaky with this one. Now you get the 2SV captive login page before you can """""force reset""""" your password a.k.a. have unfettered access to the user profile edit page.
