### ISSUE TITLE
GeoIP database

### ISSUE THREAD

**Issue by WimVDK** [akeeba/loginguard#79]
One of the sites i have LoginGuard installed on keeps prompting to upgrade the GeoIP database. So i went to the documentation below and tried to download it manually. I cannot as the domain no longer resolves.

The weird thing is, that although it prompts to upgrade the database, there is a green notification above it stating "Akeeba LoginGuard is working correctly'. So i have no idea what to believe. Clicking on "Upgrade the GeoIP database" does absolutely nothing. Most likely due to the domain no longer resolving/being active

### Documentation page affected
https://github.com/akeeba/loginguard/wiki/The-backend-overview-page

### Your concern
Links to database download no longer work. Domain does not resolve

### Old documentation passage

`You can download the latest version of MaxMind GeoLite2 Country database in binary format, from [http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz](http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz.`

### New documention passage
Can't as i don't know the new location.

**Comment by nikosdion** [comment]
[MaxMind has terminated free access to their database data](https://www.akeebabackup.com/news/1727-removal-of-geographic-ip-features-from-akeeba-software.html) and we are removing these features from our software.

I had actually [already removed the code to update the GeoIP database from LoginGuard](https://github.com/akeeba/loginguard/commit/8188ececa127218e4a2c9036e0c24d37da5bde40) before their announcement since [we had stopped collecting IP addresses a year earlier](https://github.com/akeeba/loginguard/commit/b103cab50464649b4c28c360abeb450c75605e87) due to GDPR concerns – collection of IP addresses in the context of LoginGuard did not, in fact, fall under the security reasons exemption in the GDPR.

As a result I am going to mark this issue as already resolved and close it.

**Comment by WimVDK** [comment]
Didn't know that. Good to know. So basically all i have to do is wait for an update to LoginGuard which removes this code all together? Anything (easy?) i can do in the mean time to remove/hide that message? Say by commenting out some lines with # or /* */?

**Comment by nikosdion** [comment]
I'll be releasing new versions of just about everything next week.

**Comment by WimVDK** [comment]
I'll wait then. Thanks for the quick response! I suppose the LoginGuard doc will be updated at the same time. In the mean time, i hope you had a nice holiday period. All the best to the entire team, and don't overwork yourselfs the next few weeks with removing and testing the removed-geo code :)

See you over at the akeeba site!

**Comment by WimVDK** [comment]
If you'll endulge me Nicholas, I have 1 final question. But more in relation to admin tools.

Will you be removing ALL IP logging functionality or just the geoip functions. Reason for asking is that I'm using the [IP] tag in my security exception notification to make a link to abuseipdb.com to report it. Will that functionality remain operational?

Don't use the Geo blocking itself, precisely for the spoofing possibilities.

**Comment by nikosdion** [comment]
The IP **address** has nothing to do with geolocation. The IP address is still available. Showing the **country** or **continent** will not and will always yield Unknown, exactly as I've written in the announcement.

**Comment by WimVDK** [comment]
That's all I needed to know. Many thanks for your time and patience.
