### ISSUE TITLE
Language constant not recognized

### ISSUE THREAD

**Issue by Kostelano** [akeeba/loginguard#81]
Good afternoon! A small problem: a constant is not recognized in the component settings, although there is a translation for it in Joomla.

`COM_MODULES_CUSTOM_POSITION`

![Screenshot_2](https://user-images.githubusercontent.com/8440661/82080454-3f33db00-96ed-11ea-8e9d-9d750cb32ec2.png)

**Comment by nikosdion** [comment]
Hm, this is actually a problem in Joomla. It uses a hardcoded language key without loading the respective language file. Unfortunately, the configuration page is also rendered by Joomla core code. We only provide an .xml form file. We can't tell it to load a language file for a different extension, even if it's a core one. We'd have to use a custom field that renders nothing in the form to load the language string... Sorry, I'm not gonna bother. Wasting 30' on a complicated solution for an untranslated string that's put there because Joomla did something wrong is not something I'm interested in fixing. IMHO Joomla should be addressing that problem in core code, not us doing a weird workaround for it.
