### ISSUE TITLE
[OTHER] Remember Me always Yes when page reloads

### ISSUE THREAD

**Issue by Kostelano** [akeeba/loginguard#82]
Good afternoon! I'm not sure if this is a bug, so I am writing in the other queries section.

The Remember Me feature is enabled and the mail method is used (for example). When authorizing on the site for the checkbox Remember me, I set the value to NO. If I enter the wrong code by mail (for example) or just reload the page, then the Remember me checkbox will return to the YES position. Thus, the user may accidentally mark the checkbox (skip, not pay attention), although initially set NO and did not want to use such a function.

I can’t say that this is a very serious problem, however, in my humble opinion, it is better that the value of the Remember me function does NOT change when the page is reloaded. The global decision to "enable the function remember me" is made by the administrator, but the end user makes the decision to use or NOT use the function.

Thank.

**Comment by nikosdion** [comment]
This is not a bug, it's how it's supposed to work. You cannot preserve state when you are in a captive login context.

Moreover, I extremely strongly disagree with the assertion that the user is not in control of that option! The checkbox is there and it DOES work. If you deselect it your 2SV won't be remembered on that browser. Whether you choose it or not is up to you, the user. If you made a mistake authenticating and then you blindly do something without looking at your screen that's YOUR problem as a user, not mine as a developer. I am not your nanny.

**Comment by nikosdion** [comment]
I also want to say that I appreciate you going through all free extensions on your own time and testing everything you can. But please do take a look at the documentation first :) If something isn't stated there that it works one way but behaves another it's not a bug. If you want to ask a question please use the "question" label when filing your issue. In this case please do think about whether your question is something that can already be addressed in a different way, using existing features.

In most case things work the way they do for a good reason. The Remember Me box is checked by default first and foremost because of WebAuthn and U2F. In those interactions the user is presented with a modal action by their browser. What you propose would require to cancel that dialog, click the Remember Me checkbox, click the button to select a different authentication method, select WebAuthn or U2F again and then authenticate. This might just as well be a passport control checkpoint in the former Soviet Union! The flow right now is login, tap a button on your physical authentication device, you're logged in and remembered for a short period of time.

Regarding remembering the user's state, this causes a problem because it can only be implemented as a user session state variable. This requires resetting it on login and then persisting it until the login is complete. What you propose would require setting it to No at login time because it needs an initial state. However, this means that Remember Me would work exactly ONCE before 2SV was required again. The reason is that the second login, where you're not asked for 2SV, the Remember Me checkbox state would be Off, therefore LoginGuard would believe that the user doesn't want their 2SV to be remembered. Trying to work around that by reading the preference on login opens the Remember Me feature to abuse which could be used to circumvent 2SV. That's why I said that you cannot preserve the state in a captive login context.

The only way this feature can reasonable _and securely_ work is by having the box checked by default. The user CAN choose to disable it, e.g. on shared computers, when they provide the authentication credentials. If they are on a shared computer and they don't pay attention... sorry, that's a failure on the user's part.

Anyway, the way this feature is implemented right now makes sense for the overwhelming majority of user interactions and does allow users to disable it.
