### ISSUE TITLE
loop on login

### ISSUE THREAD

**Issue by Jejomus** [akeeba/loginguard#89]
Hi,

Sorry if the way I am explaining this issue is not correct, it is my very first post on Github.

Since a few days our website users were not able to login with loginguard enabled. Once credentials entered,  "index.php/component/loginguard/?view=Captive" is reloaded every 4 seconds entering in a loop.

I tested it on Chrome and Firefox. Loginguard was working fine since a few monthes. It suddenly stopped to work while nothing on Joomla has been updated nor installed. 

Solution:

It seems that "murmurHash3js.js" was not loaded anymore.

So I have downloaded "murmurHash3js.js" locally and replaced line 21 of "loginguard/component/frontend/View/Captive/tmpl/fingerprint.php" by

$this->addJavascriptFile('media://com_loginguard/js/murmurHash3js.js', null, 'text/javascript', true, false);

Then it works again.

I hope it helps.

Kind Regards,

**Comment by nikosdion** [comment]
I assume that you download this file from the same URL LoginGuard uses. If that's the case, the problem is that something in your site's configuration is preventing loading this external resource. The most likely culprit would be Content Security Policy headers. You need to include all external locations in the script-src section. Since this header cannot be controlled by LoginGuard it's not actually a bug. It's a matter of not configuring your site correctly.

**Comment by nikosdion** [comment]
I just realised what the problem was. We're loading that file from CloudFlare's CDN. But CloudFlare was down yesterday and is still trying to recover today after a major incident with one of their upstream providers, CenturyLink. So it's not a bug in LoginGuard, it's CloudFlare being broken.
