### ISSUE TITLE
How to programmatically validate the TSV code from our own API?

### ISSUE THREAD

**Issue by asiby** [akeeba/loginguard#96]
Hello

We have a mobile app that is authenticating users using a REST API which is sitting on top of Joomla!. The login endpoint of the API receives the username and the password among other things. I looked at the LoginGuard code and found that I can possibly try to call the `Captive` view (in `com_loginguard`). But I am noticing that I could easily find myself going down a rabbit hole.

Is there a simpler approach that I am not aware of? For example, making a call similar to `$this->container->platform->runPlugins('onLoginGuardTfaValidate', [$record, $user, $code]);`, etc.

Any reply is greatly appreciated.

Keep up the great work you are doing.

Thank you!

**Comment by nikosdion** [comment]
I disagree on principle with the whole approach. Two Step Verification is meant to be used for interactive logins. The initial login (e.g. username and password) takes place and then the user is "trapped" in a locked state which does not allow them to see the site's content except for interacting with the second verification step. The second verification step is _ideally_ something which cannot be automated remotely to make it unphishable, e.g. WebAuthn, U2F etc. 

What you are trying to do is send the second step's verification code with the login information. This is no longer two step verification, it's two factor authentication of the kind that Joomla implemented as a stop-gap back in 2012 but never got upgraded to real 2SV. I know that for a fact because I was the developer that contributed Joomla's Two Factor Authentication and I know the parameters set and the discussion behind it at the time.

The problem with your approach is that it would completely break the purpose of 2SV. Your API client would need to store all information required for logging into the site (username, password and presumably the key for TOTP authentication). That makes no sense. Moreover, a RESTful API implies a stateless approach, i.e. you cannot have an API call to login, an API call for 2SV and then API calls for everything else all linked together with cookies. That's not REST.

REST has solved the 2SV problem with OAuth2. The user interactively logs into the site, goes through 2SV, a code is generated and sent back to the client. The client exchanges this code with a token. The token is used for authentication in all API calls.

Implementing OAuth2 doesn't make sense in the context of your RESTful API since there's only one tenant in the API. In this case you can follow the same approach as FOF 3.6+ or Joomla 4 (same code, I contributed FOF's code to Joomla) where a user can interactively log into the site, go through 2SV and get a token. They can then copy that token to the client's configuration. The client will be using the token for authentication.

For the token generation you can check the [FOF User Token plugin](https://github.com/akeeba/fof/tree/development/plugins/user/foftoken). This code was contributed to Joomla 4 for its own API authentication. As you can see only a token seed is stored in the database. The token is generated as an HMAC-SHA256 of that value with the site's secret which is stored in the `configuration.php` file. This makes it resilient to SQL injection attacks against the CMS application or any of its extensions. As for the authentication, check both FOF's Joomla platform class (loginUser method) and https://github.com/akeeba/fof/blob/development/plugins/user/foftoken/foftoken.php#L554

Note that REST is stateless, therefore you should never keep the user authenticating through REST logged in (normally you shouldn't be even sending cookies but in Joomla 3 it's almost impossible not to without a system plugin and a lot of trickery). This means that you need to log in the user when entering the API endpoint, i.e. when you check their token for validity, and log out the user right before the API returns any content. This is what FOF 3.6+ does with its transparent authentication. Note that the transparent authentication is currently being migrated to using the FOF token instead of allowing for username and password logins. Because the login and logout take place within the same page load, clearing the session, the redirection set by LoginGuard won't apply – especially if you close the CMS application after returning your API response instead of letting Joomla run all its plugins and handle application termination.

**Comment by asiby** [comment]
Thanks for your answer @nikosdion. Before reading the the full answer, I am going to respond to your first sentence because I am in the middle of something at the moment. I will read the entire answer later this AM.

You go it wrong BTW. I have never said that I am sending the TSV code along with the username and password. I have just skip those low level implementation details in order to get straight to the question.

The goal here is to login as usual, then the mobile app will receive a response (200, 401, etc.). Based on that response, the app will either stay on the login page or show a second screen that will be used for sending the TSV code. That's when my question applies.

**Comment by nikosdion** [comment]
> You go it wrong BTW. I have never said that I am sending the TSV code along with the username and password.

No, I didn't, for two reasons.

First, you told me that you are building a REST API. REST is stateless. The only way to make your misguided approach work in a stateless manner is passing the username, password AND second factor in the API call.

If you are not doing that it's not a REST API and I explicitly covered that base as I was pretty sure that if you're misguided enough to try and reproduce 2SV in an API you're probably doing REST wrong anyway. Here's what I wrote, word for word:

> Moreover, a RESTful API implies a stateless approach, i.e. you cannot have an API call to login, an API call for 2SV and then API calls for everything else all linked together with cookies. That's not REST.

What you described you're trying to do is even worse from both a user experience AND a security point of view. It's not RESTful, it's transmitting raw user credentials, it's creating an endpoint that can be abused to brute force OTPs at scale and doesn't even support unphishable second authentication factors such as WebAuthn. As for user experience, you will be asking the user to do the login ceremony every time they are trying to use the app which is absurd as much as it is unnecessary. All of that is addressed by using tokens for authentication.

PS: I have written an app in Flutter for our own site, retrieving some vital information I need to be able to check at a glance. This is where the need for implementing a solid token authentication flow came from. I understand your use case, that's why I am telling how to do it, not just to not do what you're trying to do.

**Comment by asiby** [comment]
We are not trying to use a stateful REST API at the moment and we are not planning to do so. Currently, upon login, a token is being provided for the mobile client, which is then used for the subsequent calls. Our API is a multi tenant one by the way.

I understand everything you are saying, and you are right. I agree with you. Thanks for the helpful information. But I have to take it from here because I can sense in the tone and wording that you are so carefully using that I have triggered you somehow. If I did, then that was far from my intentions. It's turning this conversation into an aggressive one instead of being just constructive.

Thanks again for your time. I have nice day.

**Comment by asiby** [comment]
I will close the discussion so that we can all go back to our regular activities.

**Comment by nikosdion** [comment]
I am not arbitrarily assuming that your API is RESTful. This is what you told me in the first sentence of your issue:

> We have a mobile app that is authenticating users **using a REST API** which is sitting on top of Joomla!.

So is it REST or is it not? I don't think you have fully internalized this:

> We are not trying to use a stateful REST API at the moment and we are not planning to do so. Currently, upon login, a token is being provided for the mobile client, which is then used for the subsequent calls. 

So, it _is_ REST even though you insist it's not :) Remember that REST is not about implementing a CRUD API. It's about the API being stateless. The fact that you _are_ trying to generate a token shows that you _do_ understand that your API needs to be stateless, so you're very much into the path of a RESTful API. That's good!

What is misguided -- and I insist on calling it misguided, not "stupid" or "reckless", i.e. I am simply saying that you are doing something because you didn't know why not to -- is the way you go about generating the token. It's not your API's responsibility to log in the user, verify 2SV and so on. This is what Joomla itself is and should be doing. Your app should open a webview to Joomla's login which should end up with a final redirection that generates a token and returns it to your application. That's all I am saying. It's not aggressive, it's constructive feedback. I've been bitten by doing password authentication via API and I'm sharing my experience here. Ignore it at your own risk and peril. It's already costed _me_ four years of trying to figure out a way to fix it without screwing over everyone else using my original, bad implementation.

To have a clear overview of the correct approach try using Gmail, Dropbox etc on Android/iOS to see how they do it. I think that they way multi-billion tech giants with dedicated teams of security experts solved the problem of multifactor authorisation for remote APIs is the right way to do it, exactly because they could and did afford to spend millions in security. After all, I have been very clear that LoginGuard doesn't try to reinvent the wheel, it simply implements the very round wheel these companies invented in Joomla.

> Our API is a multi tenant one by the way.

No, it's not. I think there's a confusion here. Tenants and users are different things. Think of your site as a department store. A single tenant shop would be a simple department store which manages all of its sales. All the clients getting into the store will only ever purchase something from one tenant, the company that owns the department store. A multi-tenant application is like a mall. One company owns the mall and possibly some of the flagship stores in it. However, third party companies may lease space in the mall and set up their own shops. A user (client) gets into the store (log into the app) but needs to authenticate (pay) to a different tenant (shop) every time. Just because you paid at one store doesn't magically transfer your payment information to all other stores even though they are in the same multi-tenant mall.

Since you have only a first-party application you have a single tenant server application. That's why implementing a full OAuth2 server is an overkill. Joomla had this internal discussion a few months ago. The Joomla 4 API application is a single tenant one which is why each Joomla user gets a singular API token for all access to the site over the API.

That's a very long and convoluted way of saying that all you need is one token per user and what matters is how you generate it. Reinventing credentials (username and password) login and two step verification is unproductive, it overcomplicates your API, it introduces a UX issue and most importantly it hurts your site's security. As I already said, you are explicitly removing support for WebAuthn by following that path and that's a MAJOR issue that WILL come to bite you.

This is not me being combative. I have done a lot of work in that area, both in my software and the Joomla 4 core. The future of the web _is_ WebAuthn, especially now that it has mainstream support from all major desktop and mobile OS. If you implement a webview with a standard Joomla login you're in track for a pleasant and secure user login experience once you get to Joomla 4, using WebAuthn. The user registers their mobile device's biometrics as a WebAuthn authenticator and then they can log in (without the need for 2SV!) using their fingerprint or face. This is not just convenient, it's far more secure than usernames, passwords and OTPs. If you want to do that in Joomla 3 see https://github.com/akeeba/passwordless Don't put yourself in a position that makes it impossible to use this in your mobile application without even getting any gains (just drawbacks). Again, this is me trying to save you a hundred or so hours 2-3 years down the line. Login security is my second area of expertise after taking and restoring backups.

Anyway, it's your code and your decision. If you want to do what I was doing seven years ago only to realize in a later time it was a bad idea, sure, go ahead. All I am saying here is that I've been there, done that, it sucked hairy balls after all and I am hereby offering you my experience so you don't have to suffer like I did.

**Comment by asiby** [comment]
> So, it is REST even though you insist it's not :)

You know, this is really a one sided conversation. Again, I have never said that it was not REST. I just said that it was not a **stateful** REST. I have now completely lost interest in maintaining the conversation (no offence). I tried to read this new reply but after reading "So, it is REST even though you insist it's not :)", I realized that simple messages are being understood different. It's not worth stretching this any further.

Thanks again for your time.

**Comment by nikosdion** [comment]
REST = REpresentational State Transfer. Therefore REST _is_ stateless. It always is. If it's not stateless it's not REST. Therefore you have no fucking clue what you're doing.

It's not productive talking to a moron who can't even use basic terminology right while insisting that he does. So... here's the only productive thing I can do. Lock and kick. Adios!
