### ISSUE TITLE
Changing the time before code resets

### ISSUE THREAD

**Issue by nerdy22** [akeeba/loginguard#97]
Some of users on my site have a problem with their codes being invalid. This is probably because of the email system that they use or that they are just being too slow.
I read that the codes change every 30 second.
Is there away to increase the time between code changes?

**Comment by nikosdion** [comment]
You cannot currently change the period for the generated code at the moment. In the next version you will be able to select 30 seconds, one minute, 2 minutes, 3 minutes or 5 minutes. Do note that the actual time a code is valid is up to **twice** the code's period since the time the code is generated. That is to say, with a period of 5 minutes the code will be valid for 5 to 10 minutes depending on when exactly the code was generated.

Also note that increasing the period makes it easier for an attacker to brute force the code, bypassing the Two Step Verification. A period of 5 minutes is **ten times** less secure than a period of 30 seconds. So, you need to be very careful not to increase the period beyond how much you really need it. 2-3 minutes would be ideal for most practical purposes. If your clients need longer to receive their emails you should consider using a different two step verification method altogether.

**Comment by nikosdion** [comment]
Closed with https://github.com/akeeba/loginguard/commit/45f75a45f84220d060d6292a26e8760c3d9414a9
